ModuleInfo "Version: 1.01"
ModuleInfo "Author: Mark Sibly"
ModuleInfo "License: Blitz Shared Source Code"
ModuleInfo "Copyright: Blitz Research Ltd"
ModuleInfo "Modserver: BRL"
import brl.blitz
import brl.stream
TXEndianStream^brl.stream.TStreamWrapper{
-New%()="_brl_endianstream_TXEndianStream_New"
-Swap2%(buf@*)="_brl_endianstream_TXEndianStream_Swap2"
-Swap4%(buf@*)="_brl_endianstream_TXEndianStream_Swap4"
-Swap8%(buf@*)="_brl_endianstream_TXEndianStream_Swap8"
-ReadShort%()="_brl_endianstream_TXEndianStream_ReadShort"
-WriteShort%(n%)="_brl_endianstream_TXEndianStream_WriteShort"
-ReadInt%()="_brl_endianstream_TXEndianStream_ReadInt"
-WriteInt%(n%)="_brl_endianstream_TXEndianStream_WriteInt"
-ReadLong%%()="_brl_endianstream_TXEndianStream_ReadLong"
-WriteLong%(n%%)="_brl_endianstream_TXEndianStream_WriteLong"
-ReadFloat#()="_brl_endianstream_TXEndianStream_ReadFloat"
-WriteFloat%(n#)="_brl_endianstream_TXEndianStream_WriteFloat"
-ReadDouble!()="_brl_endianstream_TXEndianStream_ReadDouble"
-WriteDouble%(n!)="_brl_endianstream_TXEndianStream_WriteDouble"
+Create:brl.stream.TStream(stream:brl.stream.TStream)="_brl_endianstream_TXEndianStream_Create"
+BigEndian:brl.stream.TStream(stream:brl.stream.TStream)="_brl_endianstream_TXEndianStream_BigEndian"
+LittleEndian:brl.stream.TStream(stream:brl.stream.TStream)="_brl_endianstream_TXEndianStream_LittleEndian"
}="brl_endianstream_TXEndianStream"
BigEndianStream:brl.stream.TStream(stream:brl.stream.TStream)="brl_endianstream_BigEndianStream"
LittleEndianStream:brl.stream.TStream(stream:brl.stream.TStream)="brl_endianstream_LittleEndianStream"
TXEndianStreamFactory^brl.stream.TStreamFactory{
-New%()="_brl_endianstream_TXEndianStreamFactory_New"
-CreateStream:brl.stream.TStream(url:Object,proto$,path$,readable%,writeable%)="_brl_endianstream_TXEndianStreamFactory_CreateStream"
}="brl_endianstream_TXEndianStreamFactory"
